/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface DocOptions { 
    blockSeparator?: DocOptions.BlockSeparatorEnum;
    blockSeparatorRex?: string;
    langList?: Array<DocOptions.LangListEnum>;
    supportMapping?: boolean;
    supportTitle?: boolean;
}
export namespace DocOptions {
    export type BlockSeparatorEnum = 'BLANK_LINE' | 'LINE_BREAK' | 'REGEX_EXPRESS';
    export const BlockSeparatorEnum = {
        BLANKLINE: 'BLANK_LINE' as BlockSeparatorEnum,
        LINEBREAK: 'LINE_BREAK' as BlockSeparatorEnum,
        REGEXEXPRESS: 'REGEX_EXPRESS' as BlockSeparatorEnum
    };
    export type LangListEnum = 'UNKNOWN' | 'AF' | 'AN' | 'AR' | 'BE' | 'BR' | 'CA' | 'BG' | 'BN' | 'CS' | 'CY' | 'DA' | 'DE' | 'EL' | 'EN' | 'ES' | 'ET' | 'EU' | 'FA' | 'FI' | 'FR' | 'GA' | 'GL' | 'GU' | 'HE' | 'HI' | 'HR' | 'HT' | 'HU' | 'ID' | 'IS' | 'IT' | 'JA' | 'KM' | 'KN' | 'KO' | 'LT' | 'LV' | 'MK' | 'ML' | 'MR' | 'MS' | 'MT' | 'NE' | 'NL' | 'NO' | 'OC' | 'PA' | 'PL' | 'PT' | 'RO' | 'RU' | 'SK' | 'SL' | 'SO' | 'SQ' | 'SR' | 'SV' | 'SW' | 'TA' | 'TE' | 'TH' | 'TL' | 'TR' | 'UK' | 'UR' | 'VI' | 'WA' | 'YI' | 'AST' | 'ZH_CN' | 'ZH_TW';
    export const LangListEnum = {
        UNKNOWN: 'UNKNOWN' as LangListEnum,
        AF: 'AF' as LangListEnum,
        AN: 'AN' as LangListEnum,
        AR: 'AR' as LangListEnum,
        BE: 'BE' as LangListEnum,
        BR: 'BR' as LangListEnum,
        CA: 'CA' as LangListEnum,
        BG: 'BG' as LangListEnum,
        BN: 'BN' as LangListEnum,
        CS: 'CS' as LangListEnum,
        CY: 'CY' as LangListEnum,
        DA: 'DA' as LangListEnum,
        DE: 'DE' as LangListEnum,
        EL: 'EL' as LangListEnum,
        EN: 'EN' as LangListEnum,
        ES: 'ES' as LangListEnum,
        ET: 'ET' as LangListEnum,
        EU: 'EU' as LangListEnum,
        FA: 'FA' as LangListEnum,
        FI: 'FI' as LangListEnum,
        FR: 'FR' as LangListEnum,
        GA: 'GA' as LangListEnum,
        GL: 'GL' as LangListEnum,
        GU: 'GU' as LangListEnum,
        HE: 'HE' as LangListEnum,
        HI: 'HI' as LangListEnum,
        HR: 'HR' as LangListEnum,
        HT: 'HT' as LangListEnum,
        HU: 'HU' as LangListEnum,
        ID: 'ID' as LangListEnum,
        IS: 'IS' as LangListEnum,
        IT: 'IT' as LangListEnum,
        JA: 'JA' as LangListEnum,
        KM: 'KM' as LangListEnum,
        KN: 'KN' as LangListEnum,
        KO: 'KO' as LangListEnum,
        LT: 'LT' as LangListEnum,
        LV: 'LV' as LangListEnum,
        MK: 'MK' as LangListEnum,
        ML: 'ML' as LangListEnum,
        MR: 'MR' as LangListEnum,
        MS: 'MS' as LangListEnum,
        MT: 'MT' as LangListEnum,
        NE: 'NE' as LangListEnum,
        NL: 'NL' as LangListEnum,
        NO: 'NO' as LangListEnum,
        OC: 'OC' as LangListEnum,
        PA: 'PA' as LangListEnum,
        PL: 'PL' as LangListEnum,
        PT: 'PT' as LangListEnum,
        RO: 'RO' as LangListEnum,
        RU: 'RU' as LangListEnum,
        SK: 'SK' as LangListEnum,
        SL: 'SL' as LangListEnum,
        SO: 'SO' as LangListEnum,
        SQ: 'SQ' as LangListEnum,
        SR: 'SR' as LangListEnum,
        SV: 'SV' as LangListEnum,
        SW: 'SW' as LangListEnum,
        TA: 'TA' as LangListEnum,
        TE: 'TE' as LangListEnum,
        TH: 'TH' as LangListEnum,
        TL: 'TL' as LangListEnum,
        TR: 'TR' as LangListEnum,
        UK: 'UK' as LangListEnum,
        UR: 'UR' as LangListEnum,
        VI: 'VI' as LangListEnum,
        WA: 'WA' as LangListEnum,
        YI: 'YI' as LangListEnum,
        AST: 'AST' as LangListEnum,
        ZHCN: 'ZH_CN' as LangListEnum,
        ZHTW: 'ZH_TW' as LangListEnum
    };
}
