/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SegItem { 
    contents?: { [key: string]: string; };
    language?: SegItem.LanguageEnum;
    titles?: { [key: string]: string; };
}
export namespace SegItem {
    export type LanguageEnum = 'UNKNOWN' | 'AF' | 'AN' | 'AR' | 'BE' | 'BR' | 'CA' | 'BG' | 'BN' | 'CS' | 'CY' | 'DA' | 'DE' | 'EL' | 'EN' | 'ES' | 'ET' | 'EU' | 'FA' | 'FI' | 'FR' | 'GA' | 'GL' | 'GU' | 'HE' | 'HI' | 'HR' | 'HT' | 'HU' | 'ID' | 'IS' | 'IT' | 'JA' | 'KM' | 'KN' | 'KO' | 'LT' | 'LV' | 'MK' | 'ML' | 'MR' | 'MS' | 'MT' | 'NE' | 'NL' | 'NO' | 'OC' | 'PA' | 'PL' | 'PT' | 'RO' | 'RU' | 'SK' | 'SL' | 'SO' | 'SQ' | 'SR' | 'SV' | 'SW' | 'TA' | 'TE' | 'TH' | 'TL' | 'TR' | 'UK' | 'UR' | 'VI' | 'WA' | 'YI' | 'AST' | 'ZH_CN' | 'ZH_TW';
    export const LanguageEnum = {
        UNKNOWN: 'UNKNOWN' as LanguageEnum,
        AF: 'AF' as LanguageEnum,
        AN: 'AN' as LanguageEnum,
        AR: 'AR' as LanguageEnum,
        BE: 'BE' as LanguageEnum,
        BR: 'BR' as LanguageEnum,
        CA: 'CA' as LanguageEnum,
        BG: 'BG' as LanguageEnum,
        BN: 'BN' as LanguageEnum,
        CS: 'CS' as LanguageEnum,
        CY: 'CY' as LanguageEnum,
        DA: 'DA' as LanguageEnum,
        DE: 'DE' as LanguageEnum,
        EL: 'EL' as LanguageEnum,
        EN: 'EN' as LanguageEnum,
        ES: 'ES' as LanguageEnum,
        ET: 'ET' as LanguageEnum,
        EU: 'EU' as LanguageEnum,
        FA: 'FA' as LanguageEnum,
        FI: 'FI' as LanguageEnum,
        FR: 'FR' as LanguageEnum,
        GA: 'GA' as LanguageEnum,
        GL: 'GL' as LanguageEnum,
        GU: 'GU' as LanguageEnum,
        HE: 'HE' as LanguageEnum,
        HI: 'HI' as LanguageEnum,
        HR: 'HR' as LanguageEnum,
        HT: 'HT' as LanguageEnum,
        HU: 'HU' as LanguageEnum,
        ID: 'ID' as LanguageEnum,
        IS: 'IS' as LanguageEnum,
        IT: 'IT' as LanguageEnum,
        JA: 'JA' as LanguageEnum,
        KM: 'KM' as LanguageEnum,
        KN: 'KN' as LanguageEnum,
        KO: 'KO' as LanguageEnum,
        LT: 'LT' as LanguageEnum,
        LV: 'LV' as LanguageEnum,
        MK: 'MK' as LanguageEnum,
        ML: 'ML' as LanguageEnum,
        MR: 'MR' as LanguageEnum,
        MS: 'MS' as LanguageEnum,
        MT: 'MT' as LanguageEnum,
        NE: 'NE' as LanguageEnum,
        NL: 'NL' as LanguageEnum,
        NO: 'NO' as LanguageEnum,
        OC: 'OC' as LanguageEnum,
        PA: 'PA' as LanguageEnum,
        PL: 'PL' as LanguageEnum,
        PT: 'PT' as LanguageEnum,
        RO: 'RO' as LanguageEnum,
        RU: 'RU' as LanguageEnum,
        SK: 'SK' as LanguageEnum,
        SL: 'SL' as LanguageEnum,
        SO: 'SO' as LanguageEnum,
        SQ: 'SQ' as LanguageEnum,
        SR: 'SR' as LanguageEnum,
        SV: 'SV' as LanguageEnum,
        SW: 'SW' as LanguageEnum,
        TA: 'TA' as LanguageEnum,
        TE: 'TE' as LanguageEnum,
        TH: 'TH' as LanguageEnum,
        TL: 'TL' as LanguageEnum,
        TR: 'TR' as LanguageEnum,
        UK: 'UK' as LanguageEnum,
        UR: 'UR' as LanguageEnum,
        VI: 'VI' as LanguageEnum,
        WA: 'WA' as LanguageEnum,
        YI: 'YI' as LanguageEnum,
        AST: 'AST' as LanguageEnum,
        ZHCN: 'ZH_CN' as LanguageEnum,
        ZHTW: 'ZH_TW' as LanguageEnum
    };
}
