/**
 * Api Documentation
 * Api Documentation
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface TitlePatternOptions { 
    allUpperCase?: boolean;
    filterByCase?: boolean;
    filterByLang?: boolean;
    filterByLength?: boolean;
    filterByRegex?: boolean;
    lang?: TitlePatternOptions.LangEnum;
    lengthThreshold?: number;
    regexPattern?: string;
}
export namespace TitlePatternOptions {
    export type LangEnum = 'UNKNOWN' | 'AF' | 'AN' | 'AR' | 'BE' | 'BR' | 'CA' | 'BG' | 'BN' | 'CS' | 'CY' | 'DA' | 'DE' | 'EL' | 'EN' | 'ES' | 'ET' | 'EU' | 'FA' | 'FI' | 'FR' | 'GA' | 'GL' | 'GU' | 'HE' | 'HI' | 'HR' | 'HT' | 'HU' | 'ID' | 'IS' | 'IT' | 'JA' | 'KM' | 'KN' | 'KO' | 'LT' | 'LV' | 'MK' | 'ML' | 'MR' | 'MS' | 'MT' | 'NE' | 'NL' | 'NO' | 'OC' | 'PA' | 'PL' | 'PT' | 'RO' | 'RU' | 'SK' | 'SL' | 'SO' | 'SQ' | 'SR' | 'SV' | 'SW' | 'TA' | 'TE' | 'TH' | 'TL' | 'TR' | 'UK' | 'UR' | 'VI' | 'WA' | 'YI' | 'AST' | 'ZH_CN' | 'ZH_TW';
    export const LangEnum = {
        UNKNOWN: 'UNKNOWN' as LangEnum,
        AF: 'AF' as LangEnum,
        AN: 'AN' as LangEnum,
        AR: 'AR' as LangEnum,
        BE: 'BE' as LangEnum,
        BR: 'BR' as LangEnum,
        CA: 'CA' as LangEnum,
        BG: 'BG' as LangEnum,
        BN: 'BN' as LangEnum,
        CS: 'CS' as LangEnum,
        CY: 'CY' as LangEnum,
        DA: 'DA' as LangEnum,
        DE: 'DE' as LangEnum,
        EL: 'EL' as LangEnum,
        EN: 'EN' as LangEnum,
        ES: 'ES' as LangEnum,
        ET: 'ET' as LangEnum,
        EU: 'EU' as LangEnum,
        FA: 'FA' as LangEnum,
        FI: 'FI' as LangEnum,
        FR: 'FR' as LangEnum,
        GA: 'GA' as LangEnum,
        GL: 'GL' as LangEnum,
        GU: 'GU' as LangEnum,
        HE: 'HE' as LangEnum,
        HI: 'HI' as LangEnum,
        HR: 'HR' as LangEnum,
        HT: 'HT' as LangEnum,
        HU: 'HU' as LangEnum,
        ID: 'ID' as LangEnum,
        IS: 'IS' as LangEnum,
        IT: 'IT' as LangEnum,
        JA: 'JA' as LangEnum,
        KM: 'KM' as LangEnum,
        KN: 'KN' as LangEnum,
        KO: 'KO' as LangEnum,
        LT: 'LT' as LangEnum,
        LV: 'LV' as LangEnum,
        MK: 'MK' as LangEnum,
        ML: 'ML' as LangEnum,
        MR: 'MR' as LangEnum,
        MS: 'MS' as LangEnum,
        MT: 'MT' as LangEnum,
        NE: 'NE' as LangEnum,
        NL: 'NL' as LangEnum,
        NO: 'NO' as LangEnum,
        OC: 'OC' as LangEnum,
        PA: 'PA' as LangEnum,
        PL: 'PL' as LangEnum,
        PT: 'PT' as LangEnum,
        RO: 'RO' as LangEnum,
        RU: 'RU' as LangEnum,
        SK: 'SK' as LangEnum,
        SL: 'SL' as LangEnum,
        SO: 'SO' as LangEnum,
        SQ: 'SQ' as LangEnum,
        SR: 'SR' as LangEnum,
        SV: 'SV' as LangEnum,
        SW: 'SW' as LangEnum,
        TA: 'TA' as LangEnum,
        TE: 'TE' as LangEnum,
        TH: 'TH' as LangEnum,
        TL: 'TL' as LangEnum,
        TR: 'TR' as LangEnum,
        UK: 'UK' as LangEnum,
        UR: 'UR' as LangEnum,
        VI: 'VI' as LangEnum,
        WA: 'WA' as LangEnum,
        YI: 'YI' as LangEnum,
        AST: 'AST' as LangEnum,
        ZHCN: 'ZH_CN' as LangEnum,
        ZHTW: 'ZH_TW' as LangEnum
    };
}
